services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4010:4010"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    env_file: .env
    environment:
      PORT: 4010
      DATABASE_URL: postgresql://postgres:password@postgres:5432/express_template
      USE_PRISMA: "true"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
      redis:
        condition: service_started
    command: sh -c "npx prisma migrate dev && npm run dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4010/api/v1/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 45s

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    network_mode: host
    depends_on:
      - app
    volumes:
      - ./e2e:/app/e2e
      - ./playwright-report:/app/playwright-report

volumes:
  postgres_data:
  mongo_data:
  redis_data: